"""
Oracle Recruiting Cloud (Oracle HCM) API Client
===============================================

A production-ready Python client for interacting with Oracle's Recruiting Cloud ATS API.
This client supports job search, job details retrieval, and location/keyword autocomplete.

Author: Generated by Claude Code
Date: 2026-01-25
"""

import requests
from typing import Dict, List, Optional, Any
from urllib.parse import urljoin, quote
import json


class OracleRecruitingClient:
    """
    Client for Oracle Recruiting Cloud API (Oracle HCM CandidateExperience API).

    This API is used by companies like Oracle, and potentially other enterprises
    using Oracle's HCM Cloud recruiting platform.

    Base URL Pattern: https://{subdomain}.fa.{region}.oraclecloud.com
    Example: https://eeho.fa.us2.oraclecloud.com (Oracle's own careers site)
    """

    def __init__(self, base_url: str, site_number: str = "CX_45001", timeout: int = 30):
        """
        Initialize the Oracle Recruiting Cloud API client.

        Args:
            base_url: Base URL of the Oracle Cloud HCM instance
                     Example: "https://eeho.fa.us2.oraclecloud.com"
            site_number: Site number identifier (default: "CX_45001" for Oracle)
                        This may vary by company
            timeout: Request timeout in seconds (default: 30)
        """
        self.base_url = base_url.rstrip('/')
        self.site_number = site_number
        self.timeout = timeout
        self.session = requests.Session()

        # Set common headers
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            'Accept': 'application/json',
            'Accept-Language': 'en-US,en;q=0.9',
        })

    def _make_request(self, method: str, endpoint: str, **kwargs) -> Dict[str, Any]:
        """
        Make an HTTP request to the Oracle API.

        Args:
            method: HTTP method (GET, POST, etc.)
            endpoint: API endpoint path
            **kwargs: Additional arguments to pass to requests

        Returns:
            JSON response as dictionary

        Raises:
            requests.exceptions.RequestException: For network errors
            ValueError: For invalid JSON responses
        """
        url = urljoin(self.base_url, endpoint)

        try:
            response = self.session.request(
                method,
                url,
                timeout=kwargs.pop('timeout', self.timeout),
                **kwargs
            )
            response.raise_for_status()
            return response.json()
        except requests.exceptions.RequestException as e:
            print(f"Request failed: {e}")
            raise
        except json.JSONDecodeError as e:
            print(f"Invalid JSON response: {e}")
            raise ValueError("Response is not valid JSON")

    def search_jobs(
        self,
        keyword: Optional[str] = None,
        location: Optional[str] = None,
        limit: int = 14,
        offset: int = 0,
        sort_by: str = "POSTING_DATES_DESC",
        facets: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """
        Search for job requisitions.

        Args:
            keyword: Search keyword for job title, description, etc.
            location: Location filter (city, state, country)
            limit: Number of results to return (default: 14)
            offset: Pagination offset (default: 0)
            sort_by: Sort order. Options:
                    - "POSTING_DATES_DESC" (newest first)
                    - "POSTING_DATES_ASC" (oldest first)
                    - "RELEVANCY" (most relevant first)
            facets: List of facets to include. Default:
                   ["LOCATIONS", "WORK_LOCATIONS", "WORKPLACE_TYPES",
                    "TITLES", "CATEGORIES", "ORGANIZATIONS", "POSTING_DATES", "FLEX_FIELDS"]

        Returns:
            Dictionary containing job listings and metadata
        """
        if facets is None:
            facets = [
                "LOCATIONS", "WORK_LOCATIONS", "WORKPLACE_TYPES",
                "TITLES", "CATEGORIES", "ORGANIZATIONS", "POSTING_DATES", "FLEX_FIELDS"
            ]

        facets_str = ";".join(facets)

        # Build finder parameters
        finder_params = [
            f"siteNumber={self.site_number}",
            f"facetsList={facets_str}",
            f"limit={limit}",
        ]

        if keyword:
            finder_params.append(f'keyword="{keyword}"')

        if offset > 0:
            finder_params.append(f"offset={offset}")

        finder_params.append(f"sortBy={sort_by}")

        finder_string = ",".join(finder_params)

        endpoint = (
            f"/hcmRestApi/resources/latest/recruitingCEJobRequisitions"
            f"?onlyData=true"
            f"&expand=requisitionList.workLocation,requisitionList.otherWorkLocations,"
            f"requisitionList.secondaryLocations,flexFieldsFacet.values,requisitionList.requisitionFlexFields"
            f"&finder=findReqs;{finder_string}"
        )

        return self._make_request('GET', endpoint)

    def get_job_details(self, job_id: str) -> Dict[str, Any]:
        """
        Get detailed information about a specific job requisition.

        Args:
            job_id: The job requisition ID

        Returns:
            Dictionary containing detailed job information
        """
        endpoint = (
            f"/hcmRestApi/resources/latest/recruitingCEJobRequisitionDetails"
            f"?expand=all"
            f"&onlyData=true"
            f'&finder=ById;Id="{job_id}",siteNumber={self.site_number}'
        )

        return self._make_request('GET', endpoint)

    def get_job_apply_flow(self, requisition_number: str) -> Dict[str, Any]:
        """
        Get the application flow configuration for a job.

        Args:
            requisition_number: The job requisition number

        Returns:
            Dictionary containing apply flow information
        """
        endpoint = (
            f"/hcmRestApi/resources/latest/recruitingCEApplyFlows"
            f'?finder=findByRequisitionNumber;RequisitionNumber="{requisition_number}"'
        )

        return self._make_request('GET', endpoint)

    def autocomplete_keywords(self, query: str, limit: int = 3) -> Dict[str, Any]:
        """
        Get autocomplete suggestions for job search keywords.

        Args:
            query: The search query to autocomplete
            limit: Maximum number of suggestions (default: 3)

        Returns:
            Dictionary containing autocomplete suggestions
        """
        endpoint = (
            f"/hcmRestApi/resources/latest/recruitingCESearchAutoSuggestions"
            f"?expand=all"
            f"&onlyData=true"
            f"&finder=findByKey;string={quote(query)}&limit={limit}"
        )

        return self._make_request('GET', endpoint)

    def autocomplete_locations(self, query: str, limit: int = 20) -> Dict[str, Any]:
        """
        Get autocomplete suggestions for location searches.

        Args:
            query: The location query to autocomplete
            limit: Maximum number of suggestions (default: 20)

        Returns:
            Dictionary containing location suggestions
        """
        endpoint = (
            f"/hcmRestApi/resources/latest/recruitingCESearchAutoSuggestions"
            f"?expand=all"
            f"&onlyData=true"
            f"&finder=findByLoc;string={quote(query)}&limit={limit}"
        )

        return self._make_request('GET', endpoint)

    def search_events(
        self,
        keyword: Optional[str] = None,
        limit: int = 14,
        offset: int = 0,
        sort_by: str = "EVENT_DATE_DESC",
        facets: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """
        Search for recruiting events.

        Args:
            keyword: Search keyword for events
            limit: Number of results to return (default: 14)
            offset: Pagination offset (default: 0)
            sort_by: Sort order (default: "EVENT_DATE_DESC")
            facets: List of facets (default: ["START_DATES", "LOCATIONS", "EVENT_CATEGORIES", "EVENT_FORMATS"])

        Returns:
            Dictionary containing event listings
        """
        if facets is None:
            facets = ["START_DATES", "LOCATIONS", "EVENT_CATEGORIES", "EVENT_FORMATS"]

        facets_str = ";".join(facets)

        finder_params = [
            f"siteNumber={self.site_number}",
            f"limit={limit}",
            f"facetsList={facets_str}",
        ]

        if keyword:
            finder_params.append(f'keyword="{keyword}"')

        if offset > 0:
            finder_params.append(f"offset={offset}")

        finder_params.append(f"sortBy={sort_by}")

        finder_string = ",".join(finder_params)

        endpoint = (
            f"/hcmRestApi/resources/latest/recruitingCEEvents"
            f"?onlyData=true"
            f"&finder=findEvents;{finder_string}"
        )

        return self._make_request('GET', endpoint)

    def get_global_settings(self) -> Dict[str, Any]:
        """
        Get global configuration settings for the recruiting site.

        Returns:
            Dictionary containing global settings
        """
        endpoint = "/hcmRestApi/CandidateExperience/globalSettings"
        return self._make_request('GET', endpoint)

    def get_translations(self, language: str = "en") -> Dict[str, Any]:
        """
        Get UI translations for the recruiting site.

        Args:
            language: Language code (default: "en")

        Returns:
            Dictionary containing translations
        """
        endpoint = f"/hcmRestApi/CandidateExperience/translations?language={language}"
        return self._make_request('GET', endpoint)

    def extract_jobs_from_response(self, response: Dict[str, Any]) -> List[Dict[str, Any]]:
        """
        Helper method to extract job list from search response.

        Args:
            response: Raw API response from search_jobs()

        Returns:
            List of job dictionaries
        """
        if 'items' in response and len(response['items']) > 0:
            return response['items'][0].get('requisitionList', [])
        return []

    def extract_events_from_response(self, response: Dict[str, Any]) -> List[Dict[str, Any]]:
        """
        Helper method to extract event list from search response.

        Args:
            response: Raw API response from search_events()

        Returns:
            List of event dictionaries
        """
        if 'items' in response and len(response['items']) > 0:
            return response['items'][0].get('eventList', [])
        return []


def main():
    """
    Example usage of the Oracle Recruiting Cloud API client.
    """
    # Initialize client with Oracle's public careers site
    client = OracleRecruitingClient(
        base_url="https://eeho.fa.us2.oraclecloud.com",
        site_number="CX_45001"
    )

    print("=" * 80)
    print("Oracle Recruiting Cloud API Client - Example Usage")
    print("=" * 80)

    # Example 1: Search for software engineer jobs
    print("\n1. Searching for 'software engineer' jobs...")
    try:
        results = client.search_jobs(keyword="software engineer", limit=5)
        if 'items' in results and len(results['items']) > 0:
            # The API returns a wrapper object with requisitionList inside
            wrapper = results['items'][0]
            total_count = wrapper.get('TotalJobsCount', 0)
            jobs = wrapper.get('requisitionList', [])

            print(f"   Found {total_count} total jobs")
            print(f"   Showing {len(jobs)} results:\n")

            for idx, job in enumerate(jobs, 1):
                title = job.get('Title', 'N/A')
                job_id = job.get('Id', 'N/A')
                location = job.get('PrimaryLocation', 'N/A')
                posted = job.get('PostedDate', 'N/A')
                print(f"   {idx}. {title}")
                print(f"      ID: {job_id}")
                print(f"      Location: {location}")
                print(f"      Posted: {posted}\n")
        else:
            print("   No jobs found or unexpected response format")
    except Exception as e:
        print(f"   Error: {e}")

    # Example 2: Get job details
    print("\n2. Getting details for a specific job...")
    try:
        # Use the first job ID from search results if available
        job_id = "320918"  # Example job ID from Oracle careers
        details = client.get_job_details(job_id)
        if 'items' in details and len(details['items']) > 0:
            wrapper = details['items'][0]
            job = wrapper if 'Title' in wrapper else wrapper.get('requisitionList', [{}])[0]

            print(f"   Title: {job.get('Title', 'N/A')}")
            print(f"   Posted: {job.get('PostedDate', 'N/A')}")
            print(f"   Location: {job.get('PrimaryLocation', 'N/A')}")
            description = job.get('ExternalDescriptionInt', job.get('ShortDescriptionStr', ''))
            if description:
                print(f"   Description: {description[:200]}...")
        else:
            print("   Job not found or unexpected response")
    except Exception as e:
        print(f"   Error: {e}")

    # Example 3: Autocomplete location search
    print("\n3. Autocomplete for 'San Francisco'...")
    try:
        suggestions = client.autocomplete_locations("San Francisco")
        if 'items' in suggestions and len(suggestions['items']) > 0:
            print(f"   Found {len(suggestions['items'])} suggestions:")
            for item in suggestions['items'][:5]:
                # Location suggestions may have different field names
                location = item.get('AddressLine1') or item.get('Name') or item.get('Description', 'N/A')
                print(f"   - {location}")
        else:
            print("   No suggestions found")
    except Exception as e:
        print(f"   Error: {e}")

    # Example 4: Search recruiting events
    print("\n4. Searching for recruiting events...")
    try:
        events = client.search_events(limit=3)
        if 'items' in events and len(events['items']) > 0:
            wrapper = events['items'][0]
            event_list = wrapper.get('eventList', [])
            total_count = wrapper.get('TotalEventsCount', len(event_list))

            print(f"   Found {total_count} total events")
            if event_list:
                for idx, event in enumerate(event_list[:3], 1):
                    title = event.get('Title', 'N/A')
                    date = event.get('StartDate', 'N/A')
                    location = event.get('Location', 'N/A')
                    print(f"   {idx}. {title}")
                    print(f"      Date: {date}")
                    print(f"      Location: {location}\n")
            else:
                print("   No events in list")
        else:
            print("   No events found")
    except Exception as e:
        print(f"   Error: {e}")

    print("\n" + "=" * 80)
    print("Examples completed!")
    print("=" * 80)


if __name__ == "__main__":
    main()
